language: php

php:
  - '7.3'

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction

script:
  - phpdbg -qrr vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover
